language: node_js
node_js:
  - '7.5'
cache:
  yarn: true
  directories:
    - node_modules
    - elm-stuff/build-artifacts
branches:
  only:
    - master
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn
  - bin/install
script:
  - npm run lint
  - npm run dist
after_success: test $TRAVIS_PULL_REQUEST == 'false' && test $TRAVIS_BRANCH == 'master' && bin/deploy
env:
  global:
    secure: fiOwOZr+lvg6hsjOT5RVdpE5kWv9GxMu/gPI0onEORe6KW8ACH+e+0fy96NVKHbWgp9Rhk3w27oA9XCUmj+pnpjl16n0JuicQnmkh/Q6J0sGK79nwwnL1QeN4VPutI+HuDCXo9qSSKkykXKMEg4dZjFGj7DoR0JErt9Rl//hAoDOMiFb06fKDEnEDbKfyxwQ8SQHsdAQ0Ct8j7JKYDEiSiLwvCpuZdkX79H+j0XNF5BrApAeq7zaj7IA+X3R3dLVPJT7u/OrWg1niEBP6E+NGVdhC1CbK9J52f0fNhh4jPWoXJ/OOPoOXDISRbY35vWAUc5ybli59/Ag77L6vXP2zbqjSAjsUmpLxEPdaKFKizuCkzh8J1Pdk2N2DmTNZonivW/yLAQ2T0hzNFGI1SASEXGU2x7iOk0OUMg7lfifGkDcxo1BhP4DZl0Ea2zwLEX8trQwjHVcyMnIAOPaIESlZcN55CAM12aFBPikqMnW0CHy3uF7CETEshgheh3f3TVShI4fz6s7VZF15G8XBfpCKnNIrNptZhXTUxmNtXNuwM7eXrr1GK5Stgl0/Frrjy9TwmOQsVLKMQMDhx6OesGK3NIVT2vx7M4yaeUr9tRKELtERjdXkQ7TIgrc3MPhGMNmVudbDsljyCZzpgFWLVMGO3//rvMIfO76i0DJwI7zcpI=
